apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: clone
  labels:
    app.kubernetes.io/version: "0.2"
    build.appstudio.redhat.com/build_type: "docker"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    dev.konflux-ci/updated-datetime: ""
spec:
  params:
  - name: url
    description: Repository URL to clone from.
    type: string
  - name: revision
    description: Revision to checkout.
    type: string
    default: main
  - name: sslVerify
    description: Set the `http.sslVerify` global git config. Setting this to `false` is not advised unless you are sure that you trust your git remote.
    type: string
    default: "true"
  steps:
  - name: clone
    image: registry.fedoraproject.org/fedora-minimal:40
    script: |
      echo clone source from $(params.url) at revision $(params.revision)
  workspaces:
  - name: source
